-- =====================================================================
-- Locale_406.lua — v4.0.6 release notes and feature highlights
-- =====================================================================

TomoMod_RegisterLocale("enUS", {
    ["wn_406_forever_detection"] = "New — TomoMod now recognizes WoW: Forever as its own client flavour by combining the modern project identifier with the 1.60 version line or interface 16001, without mistaking Classic Era or Mists Classic for it.",
    ["wn_406_forever_modules"] = "Changed — Mythic+, Housing, Prey Tracker, Compass, Consumables, Skyriding and World Quests are disabled safely on Forever before initialization and forced off in defaults, profiles, imports and live toggles.",
    ["wn_406_forever_interface"] = "Changed — Unavailable option pages, QOL tabs and the Mythic+ Studio entry are removed on Forever. A login notice explains the limitations, and /tm flavor reports the detected client and compatibility decisions.",
    ["wn_406_forever_validation"] = "Internal — A dedicated 167-check bench validates client detection, database enforcement, manifest/default consistency and source guards for every blocked module.",
    ["wn_406_minimap_layout_drag"] = "Fixed — The minimap overlay is now a real TomoLayout drag surface instead of a visual layer above the native frame. The minimap can be selected and moved reliably from Layout mode even when Blizzard Edit Mode has not loaded yet.",
    ["wn_406_minimap_drag_guard"] = "Changed — Minimap position protection pauses while it is being dragged, saves the final location on release and then resumes guarding against later Blizzard layout overrides.",
    ["wn_406_gear_weight_import"] = "New — TomoGear V1.2 can import Pawn v1, Ask Mr. Robot and compatible key=value stat scales for the current specialization. Primary stat, Stamina, Critical Strike, Haste, Mastery and Versatility are supported.",
    ["wn_406_gear_import_validation"] = "New — Each specialization keeps its own imported profile. Class, specialization and primary-stat mismatches are rejected, unsupported values are ignored, and item level has no implicit weight unless ItemLevel= is provided.",
    ["wn_406_gear_independent_db"] = "Changed — TomoGear preferences and weights now live in the dedicated TomoGearDB SavedVariable, independently from TomoMod profiles and imports. Existing Gear Advisor settings are migrated automatically once.",
    ["wn_406_gear_signed_percent"] = "Changed — Item tooltips now show signed percentages for upgrades, downgrades and equal items in green, red and neutral colours. The minimum-upgrade threshold applies only to the bag arrow.",
    ["wn_406_gear_itemref"] = "Fixed — Opening an item link from chat no longer raises an 'attempt to call a nil value' error when ItemRefTooltip reaches the item post-processor without an addon-accessible AddLine method on some Midnight builds.",
    ["wn_406_gear_tooltip_guard"] = "Changed — TomoGear now checks tooltip line support and isolates every advice-line insertion. Unsupported tooltip implementations are skipped safely while the normal GameTooltip path remains unchanged.",
})

TomoMod_RegisterLocale("frFR", {
    ["wn_406_forever_detection"] = "Nouveauté — TomoMod reconnaît maintenant WoW : Forever comme un client distinct en combinant l'identifiant du projet moderne avec la version 1.60 ou l'interface 16001, sans le confondre avec Classic Era ou Mists Classic.",
    ["wn_406_forever_modules"] = "Modification — Mythique+, Logement, Traqueur de proie, Boussole, Consommables, Vol dynamique et Quêtes du monde sont désactivés proprement sur Forever avant leur initialisation et forcés à l'arrêt dans les valeurs par défaut, profils, imports et bascules directes.",
    ["wn_406_forever_interface"] = "Modification — Les pages d'options, onglets QOL et l'entrée du Studio Mythique+ indisponibles sont retirés sur Forever. Un message de connexion explique les limitations et /tm flavor indique le client détecté ainsi que les décisions de compatibilité.",
    ["wn_406_forever_validation"] = "Interne — Un banc dédié de 167 contrôles valide la détection du client, l'application aux données, la cohérence manifeste/valeurs par défaut et les gardes de chaque module bloqué.",
    ["wn_406_minimap_layout_drag"] = "Correction — La superposition de la minimap est maintenant une véritable surface de déplacement TomoLayout plutôt qu'une simple couche visuelle au-dessus du cadre natif. La minimap peut être sélectionnée et déplacée de façon fiable depuis le mode Layout, même si le mode Édition de Blizzard n'est pas encore chargé.",
    ["wn_406_minimap_drag_guard"] = "Modification — La protection de position de la minimap se met en pause pendant son déplacement, enregistre l'emplacement final au relâchement puis reprend sa protection contre les modifications ultérieures de Blizzard.",
    ["wn_406_gear_weight_import"] = "Nouveauté — TomoGear V1.2 peut importer des échelles Pawn v1, Ask Mr. Robot et key=value compatibles pour la spécialisation actuelle. La caractéristique principale, l'Endurance, le Critique, la Hâte, la Maîtrise et la Polyvalence sont pris en charge.",
    ["wn_406_gear_import_validation"] = "Nouveauté — Chaque spécialisation conserve son propre profil importé. Les incompatibilités de classe, de spécialisation ou de caractéristique principale sont refusées, les valeurs non prises en charge sont ignorées et le niveau d'objet ne reçoit aucun poids implicite sans ItemLevel=.",
    ["wn_406_gear_independent_db"] = "Modification — Les préférences et les poids de TomoGear résident maintenant dans la variable sauvegardée dédiée TomoGearDB, indépendamment des profils et imports TomoMod. Les anciens réglages du conseiller sont migrés automatiquement une seule fois.",
    ["wn_406_gear_signed_percent"] = "Modification — Les infobulles affichent maintenant un pourcentage signé pour les améliorations, régressions et objets équivalents, respectivement en vert, rouge et neutre. Le seuil minimal ne s'applique plus qu'à la flèche des sacs.",
    ["wn_406_gear_itemref"] = "Correction — Ouvrir un lien d'objet depuis la discussion ne provoque plus d'erreur 'attempt to call a nil value' lorsque ItemRefTooltip atteint le post-traitement des objets sans méthode AddLine accessible aux addons sur certaines versions de Midnight.",
    ["wn_406_gear_tooltip_guard"] = "Modification — TomoGear vérifie désormais que l'infobulle accepte l'ajout de lignes et isole chaque insertion de conseil. Les implémentations incompatibles sont ignorées proprement tandis que le fonctionnement normal de GameTooltip reste inchangé.",
})

TomoMod_RegisterLocale("deDE", {
    ["wn_406_forever_detection"] = "Neu — TomoMod erkennt WoW: Forever jetzt als eigenen Clienttyp, indem die moderne Projektkennung mit der Versionslinie 1.60 oder Interface 16001 kombiniert wird, ohne Classic Era oder Mists Classic damit zu verwechseln.",
    ["wn_406_forever_modules"] = "Geändert — Mythisch+, Wohnen, Beutejäger, Kompass, Verbrauchsgüter, dynamisches Fliegen und Weltquests werden auf Forever vor der Initialisierung sicher deaktiviert und in Standardwerten, Profilen, Importen und Live-Schaltern ausgeschaltet gehalten.",
    ["wn_406_forever_interface"] = "Geändert — Nicht verfügbare Optionsseiten, QOL-Reiter und der Eintrag für das Mythisch+-Studio werden auf Forever entfernt. Ein Hinweis beim Anmelden erklärt die Einschränkungen; /tm flavor zeigt den erkannten Client und die Kompatibilitätsentscheidungen.",
    ["wn_406_forever_validation"] = "Intern — Ein eigener Prüfstand mit 167 Kontrollen validiert Clienterkennung, Datenbankdurchsetzung, Konsistenz von Manifest und Standardwerten sowie die Schutzabfragen aller blockierten Module.",
    ["wn_406_minimap_layout_drag"] = "Behoben — Die Minimap-Überlagerung ist jetzt eine echte TomoLayout-Ziehfläche statt nur einer sichtbaren Ebene über dem nativen Fenster. Die Minimap lässt sich im Layoutmodus zuverlässig auswählen und verschieben, selbst wenn Blizzards Bearbeitungsmodus noch nicht geladen wurde.",
    ["wn_406_minimap_drag_guard"] = "Geändert — Der Positionsschutz der Minimap pausiert während des Verschiebens, speichert beim Loslassen den endgültigen Ort und schützt danach wieder vor späteren Layout-Überschreibungen durch Blizzard.",
    ["wn_406_gear_weight_import"] = "Neu — TomoGear V1.2 kann Pawn-v1-, Ask-Mr.-Robot- und kompatible key=value-Attributgewichtungen für die aktuelle Spezialisierung importieren. Primärattribut, Ausdauer, Krit, Tempo, Meisterschaft und Vielseitigkeit werden unterstützt.",
    ["wn_406_gear_import_validation"] = "Neu — Jede Spezialisierung behält ihr eigenes importiertes Profil. Unpassende Klassen, Spezialisierungen oder Primärattribute werden abgelehnt, nicht unterstützte Werte ignoriert und die Gegenstandsstufe erhält ohne ItemLevel= kein stillschweigendes Gewicht.",
    ["wn_406_gear_independent_db"] = "Geändert — TomoGear-Einstellungen und -Gewichtungen liegen jetzt unabhängig von TomoMod-Profilen und -Importen in der eigenen gespeicherten Variable TomoGearDB. Vorhandene Berater-Einstellungen werden einmalig automatisch übernommen.",
    ["wn_406_gear_signed_percent"] = "Geändert — Gegenstands-Tooltips zeigen jetzt vorzeichenbehaftete Prozentwerte für Verbesserungen, Verschlechterungen und gleichwertige Gegenstände in Grün, Rot beziehungsweise neutral an. Der Mindestwert gilt nur noch für den Taschenpfeil.",
    ["wn_406_gear_itemref"] = "Behoben — Beim Öffnen eines Gegenstandslinks aus dem Chat tritt kein Fehler 'attempt to call a nil value' mehr auf, wenn ItemRefTooltip auf manchen Midnight-Versionen den Gegenstands-Nachbearbeiter ohne eine für Addons zugängliche AddLine-Methode erreicht.",
    ["wn_406_gear_tooltip_guard"] = "Geändert — TomoGear prüft jetzt, ob ein Tooltip das Hinzufügen von Zeilen unterstützt, und sichert jedes Einfügen eines Hinweises einzeln ab. Nicht unterstützte Tooltip-Implementierungen werden sicher übersprungen, während der normale GameTooltip-Pfad unverändert bleibt.",
})

TomoMod_RegisterLocale("esES", {
    ["wn_406_forever_detection"] = "Novedad — TomoMod ahora reconoce WoW: Forever como un tipo de cliente propio al combinar el identificador del proyecto moderno con la versión 1.60 o la interfaz 16001, sin confundirlo con Classic Era ni Mists Classic.",
    ["wn_406_forever_modules"] = "Cambio — Mítico+, Vivienda, Rastreador de presas, Brújula, Consumibles, Vuelo dinámico y Misiones del mundo se desactivan de forma segura en Forever antes de iniciarse y se mantienen apagados en valores predeterminados, perfiles, importaciones y controles directos.",
    ["wn_406_forever_interface"] = "Cambio — Las páginas de opciones, pestañas QOL y la entrada del Estudio Mítico+ no disponibles se eliminan en Forever. Un aviso al iniciar sesión explica las limitaciones y /tm flavor muestra el cliente detectado y las decisiones de compatibilidad.",
    ["wn_406_forever_validation"] = "Interno — Un banco específico de 167 comprobaciones valida la detección del cliente, la aplicación sobre la base de datos, la coherencia entre manifiesto y valores predeterminados y las protecciones de cada módulo bloqueado.",
    ["wn_406_minimap_layout_drag"] = "Corrección — La capa de la minimapa ahora es una superficie de arrastre real de TomoLayout en lugar de una simple capa visual sobre el marco nativo. La minimapa puede seleccionarse y moverse de forma fiable desde el modo Layout aunque el modo Edición de Blizzard aún no se haya cargado.",
    ["wn_406_minimap_drag_guard"] = "Cambio — La protección de posición de la minimapa se pausa durante el arrastre, guarda la ubicación final al soltarla y después vuelve a protegerla frente a cambios posteriores del diseño de Blizzard.",
    ["wn_406_gear_weight_import"] = "Novedad — TomoGear V1.2 puede importar escalas Pawn v1, Ask Mr. Robot y key=value compatibles para la especialización actual. Se admiten la estadística principal, Aguante, Crítico, Celeridad, Maestría y Versatilidad.",
    ["wn_406_gear_import_validation"] = "Novedad — Cada especialización conserva su propio perfil importado. Se rechazan las escalas de otra clase, especialización o estadística principal, se ignoran los valores no compatibles y el nivel de objeto no recibe peso implícito sin ItemLevel=.",
    ["wn_406_gear_independent_db"] = "Cambio — Las preferencias y los pesos de TomoGear ahora residen en la variable guardada independiente TomoGearDB, al margen de los perfiles e importaciones de TomoMod. Los ajustes existentes del asesor se migran automáticamente una sola vez.",
    ["wn_406_gear_signed_percent"] = "Cambio — Las descripciones de objetos ahora muestran porcentajes con signo para mejoras, empeoramientos y objetos equivalentes en verde, rojo y color neutro. El umbral mínimo solo se aplica a la flecha de las bolsas.",
    ["wn_406_gear_itemref"] = "Corrección — Abrir un enlace de objeto desde el chat ya no provoca el error 'attempt to call a nil value' cuando ItemRefTooltip llega al posprocesador de objetos sin un método AddLine accesible para addons en algunas versiones de Midnight.",
    ["wn_406_gear_tooltip_guard"] = "Cambio — TomoGear ahora comprueba si la descripción admite líneas adicionales y aísla cada inserción de consejo. Las implementaciones incompatibles se omiten de forma segura, mientras que la ruta normal de GameTooltip permanece sin cambios.",
})

TomoMod_RegisterLocale("itIT", {
    ["wn_406_forever_detection"] = "Novità — TomoMod ora riconosce WoW: Forever come tipo di client distinto combinando l'identificatore del progetto moderno con la versione 1.60 o l'interfaccia 16001, senza confonderlo con Classic Era o Mists Classic.",
    ["wn_406_forever_modules"] = "Modifica — Mitica+, Alloggi, Tracciatore di prede, Bussola, Consumabili, Volo dinamico e Missioni mondiali vengono disattivati in sicurezza su Forever prima dell'inizializzazione e mantenuti spenti nei valori predefiniti, profili, importazioni e controlli diretti.",
    ["wn_406_forever_interface"] = "Modifica — Le pagine delle opzioni, le schede QOL e la voce dello Studio Mitica+ non disponibili vengono rimosse su Forever. Un avviso all'accesso spiega le limitazioni e /tm flavor mostra il client rilevato e le decisioni di compatibilità.",
    ["wn_406_forever_validation"] = "Interno — Un banco dedicato con 167 controlli verifica il rilevamento del client, l'applicazione al database, la coerenza tra manifest e valori predefiniti e le protezioni di ogni modulo bloccato.",
    ["wn_406_minimap_layout_drag"] = "Correzione — La sovrapposizione della minimappa è ora una vera superficie di trascinamento TomoLayout invece di un semplice livello visivo sopra il riquadro nativo. La minimappa può essere selezionata e spostata in modo affidabile dalla modalità Layout anche se la modalità Modifica di Blizzard non è ancora caricata.",
    ["wn_406_minimap_drag_guard"] = "Modifica — La protezione della posizione della minimappa viene sospesa durante il trascinamento, salva la posizione finale al rilascio e poi riprende a proteggerla dalle successive modifiche del layout di Blizzard.",
    ["wn_406_gear_weight_import"] = "Novità — TomoGear V1.2 può importare scale Pawn v1, Ask Mr. Robot e key=value compatibili per la specializzazione attuale. Sono supportati statistica primaria, Tempra, Critico, Celerità, Maestria e Versatilità.",
    ["wn_406_gear_import_validation"] = "Novità — Ogni specializzazione conserva il proprio profilo importato. Le scale con classe, specializzazione o statistica primaria errate vengono rifiutate, i valori non supportati ignorati e il livello oggetto non riceve alcun peso implicito senza ItemLevel=.",
    ["wn_406_gear_independent_db"] = "Modifica — Preferenze e pesi di TomoGear ora risiedono nella variabile salvata dedicata TomoGearDB, indipendentemente dai profili e dalle importazioni di TomoMod. Le impostazioni esistenti vengono migrate automaticamente una sola volta.",
    ["wn_406_gear_signed_percent"] = "Modifica — I tooltip degli oggetti mostrano ora percentuali con segno per miglioramenti, peggioramenti e oggetti equivalenti in verde, rosso e colore neutro. La soglia minima si applica soltanto alla freccia nelle borse.",
    ["wn_406_gear_itemref"] = "Correzione — L'apertura di un collegamento a un oggetto dalla chat non genera più l'errore 'attempt to call a nil value' quando ItemRefTooltip raggiunge il post-processore degli oggetti senza un metodo AddLine accessibile agli addon in alcune versioni di Midnight.",
    ["wn_406_gear_tooltip_guard"] = "Modifica — TomoGear ora verifica che il tooltip supporti l'aggiunta di righe e protegge ogni inserimento dei consigli. Le implementazioni non supportate vengono ignorate in sicurezza, mentre il normale percorso GameTooltip resta invariato.",
})

TomoMod_RegisterLocale("ptBR", {
    ["wn_406_forever_detection"] = "Novidade — O TomoMod agora reconhece o WoW: Forever como um tipo de cliente próprio ao combinar o identificador do projeto moderno com a versão 1.60 ou a interface 16001, sem confundi-lo com Classic Era ou Mists Classic.",
    ["wn_406_forever_modules"] = "Alteração — Mítico+, Moradia, Rastreador de presas, Bússola, Consumíveis, Voo dinâmico e Missões mundiais são desativados com segurança no Forever antes da inicialização e mantidos desligados nos padrões, perfis, importações e controles diretos.",
    ["wn_406_forever_interface"] = "Alteração — Páginas de opções, abas QOL e a entrada do Estúdio Mítico+ indisponíveis são removidas no Forever. Um aviso ao entrar explica as limitações, e /tm flavor mostra o cliente detectado e as decisões de compatibilidade.",
    ["wn_406_forever_validation"] = "Interno — Um conjunto dedicado de 167 verificações valida a detecção do cliente, a aplicação no banco de dados, a consistência entre manifesto e padrões e as proteções de cada módulo bloqueado.",
    ["wn_406_minimap_layout_drag"] = "Correção — A sobreposição do minimapa agora é uma superfície real de arraste do TomoLayout, em vez de apenas uma camada visual sobre o quadro nativo. O minimapa pode ser selecionado e movido de forma confiável no modo Layout mesmo que o modo de Edição da Blizzard ainda não tenha sido carregado.",
    ["wn_406_minimap_drag_guard"] = "Alteração — A proteção da posição do minimapa pausa durante o arraste, salva o local final ao soltar e depois volta a protegê-lo contra alterações posteriores do layout da Blizzard.",
    ["wn_406_gear_weight_import"] = "Novidade — O TomoGear V1.2 pode importar escalas Pawn v1, Ask Mr. Robot e key=value compatíveis para a especialização atual. Atributo primário, Vigor, Crítico, Aceleração, Maestria e Versatilidade são aceitos.",
    ["wn_406_gear_import_validation"] = "Novidade — Cada especialização mantém seu próprio perfil importado. Escalas com classe, especialização ou atributo primário incompatíveis são recusadas, valores não aceitos são ignorados e o nível do item não recebe peso implícito sem ItemLevel=.",
    ["wn_406_gear_independent_db"] = "Alteração — As preferências e os pesos do TomoGear agora ficam na variável salva dedicada TomoGearDB, independentemente dos perfis e das importações do TomoMod. As configurações existentes são migradas automaticamente uma única vez.",
    ["wn_406_gear_signed_percent"] = "Alteração — As dicas de item agora mostram percentuais com sinal para melhorias, pioras e itens equivalentes em verde, vermelho e cor neutra. O limite mínimo se aplica apenas à seta nas bolsas.",
    ["wn_406_gear_itemref"] = "Correção — Abrir um link de item pelo bate-papo não causa mais o erro 'attempt to call a nil value' quando o ItemRefTooltip chega ao pós-processador de itens sem um método AddLine acessível a addons em algumas versões do Midnight.",
    ["wn_406_gear_tooltip_guard"] = "Alteração — O TomoGear agora verifica se a dica aceita linhas adicionais e protege cada inserção de recomendação. Implementações incompatíveis são ignoradas com segurança, enquanto o fluxo normal do GameTooltip permanece inalterado.",
})
