-- =====================================================================
-- Locale_404.lua — v4.0.4 release notes and feature highlights
-- =====================================================================

TomoMod_RegisterLocale("enUS", {
    ["wn_404_tomohdv_buy_layout"] = "Fixed — TomoHDV V3.2 keeps quantity, total and status clear of the buy button on ultrawide displays and at compact UI scales. The complete direct-purchase workflow now stays inside the available height of the item sheet.",
    ["wn_404_tomohdv_buy_final_polish"] = "Changed — TomoHDV V3.3 moves the direct-purchase controls into their own card, stretched between the price cards and the confirmation button. Quantity can no longer climb into the price cards at any UI scale, and the taller, slightly wider item sheet gives the estimated total and the status line more room.",
    ["wn_404_nameplates_secret_power"] = "Fixed — Follower-dungeon role detection checks whether UnitPowerMax returned a protected value before comparing it. Unreadable mana safely falls back to the damage role instead of raising an error in restricted content.",
    ["wn_404_unitclass_safety"] = "Fixed — Forge, Damage Meter, Resource Bars, the AFK display, Cooldown Manager and Resource Cast Studio now sanitize UnitClass results before looking up class colours. If the class is protected, each interface uses a safe fallback instead of raising an error.",
    ["wn_404_profile_recovery"] = "New — TomoMod keeps the five latest recovery backups. Profiles > Resets and the /tm backup commands can create, list and restore them, while imports, layouts, presets and resets automatically create a recovery point and roll back if application fails.",
    ["wn_404_import_safety"] = "Changed — Full, selective and named-profile imports are now out-of-combat, transactional and strictly bounded. Oversized or deeply nested payloads, executable data, cycles, metatables, non-finite numbers, invalid values and non-portable settings are rejected before the live database is changed.",
    ["wn_404_layout_share_safety"] = "Fixed — Layout share strings and waypoint labels keep their original letter case instead of being lowercased by the command parser. Layout imports accept only declared anchors and font paths, validate every position and preserve resolution-aware scaling inside a recoverable transaction.",
    ["wn_404_interface_reliability"] = "Fixed — The options window reliably saves the active profile when closed, reload and import overlays stay above it, aura dragging ignores incomplete frame coordinates, and Mythic+ run analysis now uses TomoMod's shared brand accent.",
    ["wn_404_studio_return"] = "New — Opening any Studio now always hides the TomoMod GUI. Closing Mythic+, Party & Raid, Resource & Cast or Astral Forge Studio opens it again, while Cooldown Studio keeps its existing safety-reload exit without reopening the GUI behind the confirmation.",
    ["wn_404_release_validation"] = "Internal — CI now gates Lua 5.1 syntax, XML, secret-value checks, regression tests and the packaged load graph. The builder detects missing, miscased, cyclic or escaping references and invalid initialization order, including reliable casing checks on Windows.",
    ["wn_404_secret_reference"] = "New — TomoMod now ships a generated secret-value API reference from WoW 12.1.0. It records nearly 4,000 client APIDocumentation entries, including 82 widget methods that may return protected values and 85 functions that reject secret arguments.",
    ["wn_404_secret_audit"] = "Changed — The audit combines the client reference with repository evidence, adds optional widget, evidence, inconsistency and JSON reports, and uses portable baseline paths. Its expanded 70-test suite passes with no new release finding.",
})

TomoMod_RegisterLocale("frFR", {
    ["wn_404_tomohdv_buy_layout"] = "Correction — TomoHDV V3.2 garde la quantité, le total et l'état à l'écart du bouton d'achat sur les écrans ultralarges et avec une échelle d'interface réduite. L'ensemble de l'achat direct reste maintenant dans la hauteur disponible de la fiche objet.",
    ["wn_404_tomohdv_buy_final_polish"] = "Modification — TomoHDV V3.3 déplace les contrôles d'achat direct dans une carte dédiée, étirée entre les cartes de prix et le bouton de confirmation. La quantité ne peut plus remonter sur les cartes de prix, quelle que soit l'échelle d'interface, et la fiche objet plus haute et légèrement plus large laisse davantage de place au total estimé et à la ligne d'état.",
    ["wn_404_nameplates_secret_power"] = "Correction — La détection des rôles dans les donjons avec compagnons vérifie si UnitPowerMax a renvoyé une valeur protégée avant de la comparer. Une mana illisible revient sans erreur au rôle de dégâts dans le contenu restreint.",
    ["wn_404_unitclass_safety"] = "Correction — Forge, Damage Meter, Resource Bars, l'écran AFK, Cooldown Manager et Resource Cast Studio assainissent maintenant les résultats de UnitClass avant de rechercher les couleurs de classe. Si la classe est protégée, chaque interface utilise une valeur de secours sûre au lieu de provoquer une erreur.",
    ["wn_404_profile_recovery"] = "Nouveauté — TomoMod conserve les cinq dernières sauvegardes de récupération. Profils > Réinitialisations et les commandes /tm backup permettent de les créer, lister et restaurer ; imports, dispositions, presets et réinitialisations créent automatiquement un point de retour et annulent l'opération en cas d'échec.",
    ["wn_404_import_safety"] = "Modification — Les imports complets, sélectifs et comme profil nommé sont désormais transactionnels, limités et disponibles hors combat. Les charges trop volumineuses ou profondes, exécutables, cycliques, avec métatable, nombres non finis, valeurs invalides ou réglages non portables sont rejetées avant toute modification de la base active.",
    ["wn_404_layout_share_safety"] = "Correction — Les chaînes de partage de disposition et les noms de points de passage conservent leur casse au lieu d'être convertis en minuscules par les commandes. L'import accepte uniquement les ancres et polices déclarées, valide chaque position et préserve l'adaptation à la résolution dans une transaction récupérable.",
    ["wn_404_interface_reliability"] = "Correction — La fermeture des options sauvegarde fiablement le profil actif, les fenêtres de rechargement et d'import restent au premier plan, le déplacement des auras ignore les coordonnées incomplètes et l'analyse Mythic+ utilise maintenant l'accent commun de TomoMod.",
    ["wn_404_studio_return"] = "Nouveauté — Ouvrir un Studio masque maintenant toujours le GUI TomoMod. Fermer les Studios Mythic+, Groupe et Raid, Ressources et Incantations ou Astral Forge le rouvre, tandis que Cooldown Studio conserve sa sortie avec reload de sécurité sans rouvrir le GUI derrière la confirmation.",
    ["wn_404_release_validation"] = "Interne — La CI contrôle désormais la syntaxe Lua 5.1, le XML, les valeurs secrètes, les tests de régression et le graphe de chargement du paquet. Le générateur détecte les références absentes, mal capitalisées, cycliques ou sortantes et l'ordre d'initialisation invalide, y compris sous Windows.",
    ["wn_404_secret_reference"] = "Nouveauté — TomoMod fournit désormais une référence générée des API à valeurs secrètes de WoW 12.1.0. Elle recense près de 4 000 entrées APIDocumentation du client, dont 82 méthodes de widgets pouvant renvoyer des valeurs protégées et 85 fonctions refusant les arguments secrets.",
    ["wn_404_secret_audit"] = "Modification — L'audit combine la référence du client avec les preuves du dépôt, ajoute des rapports optionnels sur les widgets, les preuves et les incohérences ainsi qu'au format JSON, et utilise des chemins de baseline portables. Ses 70 tests passent sans nouvelle alerte de publication.",
})

TomoMod_RegisterLocale("deDE", {
    ["wn_404_tomohdv_buy_layout"] = "Behoben — TomoHDV V3.2 hält Menge, Summe und Status auf Ultrawide-Bildschirmen und bei kleiner UI-Skalierung von der Kaufschaltfläche frei. Der vollständige Direktkauf bleibt nun innerhalb der verfügbaren Höhe der Gegenstandsansicht.",
    ["wn_404_tomohdv_buy_final_polish"] = "Geändert — TomoHDV V3.3 verschiebt die Direktkauf-Steuerelemente in eine eigene Karte, die sich zwischen den Preiskarten und der Bestätigungsschaltfläche aufspannt. Die Menge kann bei keiner UI-Skalierung mehr in die Preiskarten wandern, und die höhere, etwas breitere Gegenstandsansicht gibt der geschätzten Summe und der Statuszeile mehr Platz.",
    ["wn_404_nameplates_secret_power"] = "Behoben — Die Rollenerkennung in Anhängerdungeons prüft vor dem Vergleich, ob UnitPowerMax einen geschützten Wert geliefert hat. Nicht lesbares Mana fällt in eingeschränkten Inhalten fehlerfrei auf die Schadensrolle zurück.",
    ["wn_404_unitclass_safety"] = "Behoben — Forge, Damage Meter, Resource Bars, die AFK-Anzeige, Cooldown Manager und Resource Cast Studio bereinigen jetzt UnitClass-Ergebnisse vor dem Abruf von Klassenfarben. Ist die Klasse geschützt, verwendet jede Oberfläche einen sicheren Ersatzwert, statt einen Fehler auszulösen.",
    ["wn_404_profile_recovery"] = "Neu — TomoMod bewahrt die fünf neuesten Wiederherstellungssicherungen auf. Unter Profile > Zurücksetzen und mit /tm backup lassen sie sich erstellen, anzeigen und wiederherstellen; Importe, Layouts, Presets und Rücksetzungen legen automatisch einen Rückkehrpunkt an und werden bei Fehlern zurückgerollt.",
    ["wn_404_import_safety"] = "Geändert — Vollständige, selektive und benannte Profilimporte sind nun transaktional, begrenzt und nur außerhalb des Kampfes verfügbar. Zu große oder tiefe Daten, ausführbarer Inhalt, Zyklen, Metatabellen, nicht endliche Zahlen, ungültige Werte und nicht übertragbare Einstellungen werden vor jeder Änderung verworfen.",
    ["wn_404_layout_share_safety"] = "Behoben — Layout-Freigabecodes und Wegpunktnamen behalten ihre Groß- und Kleinschreibung, statt vom Befehlsparser kleingeschrieben zu werden. Importe akzeptieren nur deklarierte Anker und Schriftpfade, prüfen jede Position und erhalten die auflösungsabhängige Skalierung in einer wiederherstellbaren Transaktion.",
    ["wn_404_interface_reliability"] = "Behoben — Beim Schließen der Optionen wird das aktive Profil zuverlässig gespeichert, Neulade- und Importfenster bleiben darüber sichtbar, unvollständige Koordinaten werden beim Aura-Ziehen ignoriert und die Mythic+-Laufanalyse nutzt nun TomoMods gemeinsamen Markenakzent.",
    ["wn_404_studio_return"] = "Neu — Beim Öffnen eines Studios wird die TomoMod-Oberfläche jetzt immer ausgeblendet. Beim Schließen des Mythisch+-, Gruppe-und-Schlachtzug-, Ressourcen-und-Zauber- oder Astral-Forge-Studios wird sie wieder geöffnet; Cooldown Studio behält dagegen seinen Sicherheits-Neuladeablauf bei, ohne die Oberfläche hinter der Bestätigung zu öffnen.",
    ["wn_404_release_validation"] = "Intern — CI prüft jetzt Lua-5.1-Syntax, XML, geheime Werte, Regressionstests und den Ladegraphen des Pakets. Der Builder erkennt fehlende, falsch geschriebene, zyklische oder aus dem Paket führende Verweise sowie eine falsche Initialisierungsreihenfolge, einschließlich zuverlässiger Groß-/Kleinschreibungsprüfung unter Windows.",
    ["wn_404_secret_reference"] = "Neu — TomoMod enthält jetzt eine generierte Referenz für APIs mit geheimen Werten aus WoW 12.1.0. Sie erfasst fast 4.000 APIDocumentation-Einträge des Clients, darunter 82 Widget-Methoden, die geschützte Werte zurückgeben können, und 85 Funktionen, die geheime Argumente ablehnen.",
    ["wn_404_secret_audit"] = "Geändert — Die Prüfung kombiniert die Client-Referenz mit Repository-Nachweisen, bietet optionale Widget-, Nachweis-, Inkonsistenz- und JSON-Berichte und verwendet portable Baseline-Pfade. Die erweiterte Suite mit 70 Tests besteht ohne neuen Veröffentlichungsfund.",
})

TomoMod_RegisterLocale("esES", {
    ["wn_404_tomohdv_buy_layout"] = "Corrección — TomoHDV V3.2 mantiene la cantidad, el total y el estado alejados del botón de compra en pantallas ultrapanorámicas y con escalas de interfaz reducidas. Todo el flujo de compra directa permanece ahora dentro de la altura disponible de la ficha del objeto.",
    ["wn_404_tomohdv_buy_final_polish"] = "Cambio — TomoHDV V3.3 traslada los controles de compra directa a su propia tarjeta, estirada entre las tarjetas de precio y el botón de confirmación. La cantidad ya no puede invadir las tarjetas de precio con ninguna escala de interfaz, y la ficha del objeto, más alta y algo más ancha, deja más espacio al total estimado y a la línea de estado.",
    ["wn_404_nameplates_secret_power"] = "Corrección — La detección de roles en mazmorras con seguidores comprueba si UnitPowerMax devolvió un valor protegido antes de compararlo. Si el maná no es legible, se usa el rol de daño sin provocar errores en contenido restringido.",
    ["wn_404_unitclass_safety"] = "Corrección — Forge, Damage Meter, Resource Bars, la pantalla AFK, Cooldown Manager y Resource Cast Studio ahora depuran los resultados de UnitClass antes de consultar los colores de clase. Si la clase está protegida, cada interfaz utiliza un valor alternativo seguro en vez de provocar un error.",
    ["wn_404_profile_recovery"] = "Novedad — TomoMod conserva las cinco copias de recuperación más recientes. Perfiles > Restablecimientos y los comandos /tm backup permiten crearlas, listarlas y restaurarlas; las importaciones, disposiciones, presets y restablecimientos crean un punto de retorno y revierten los cambios si fallan.",
    ["wn_404_import_safety"] = "Cambio — Las importaciones completas, selectivas y como perfil con nombre son ahora transaccionales, limitadas y solo están disponibles fuera de combate. Los datos demasiado grandes o profundos, ejecutables, cíclicos, con metatablas, números no finitos, valores inválidos o ajustes no portables se rechazan antes de modificar la base activa.",
    ["wn_404_layout_share_safety"] = "Corrección — Las cadenas de disposición y los nombres de puntos de ruta conservan sus mayúsculas y minúsculas en vez de ser alterados por el intérprete de comandos. La importación solo acepta anclajes y fuentes declarados, valida cada posición y conserva el escalado por resolución dentro de una transacción recuperable.",
    ["wn_404_interface_reliability"] = "Corrección — Al cerrar las opciones se guarda de forma fiable el perfil activo, las ventanas de recarga e importación permanecen por encima, el arrastre de auras ignora coordenadas incompletas y el análisis de Mítica+ usa ahora el color de marca compartido de TomoMod.",
    ["wn_404_studio_return"] = "Novedad — Abrir cualquier Estudio ahora oculta siempre la interfaz de TomoMod. Al cerrar los Estudios de Mítica+, Grupo y Banda, Recursos y Lanzamientos o Astral Forge se vuelve a abrir; el Estudio de Cooldowns conserva su salida con recarga de seguridad sin abrir la interfaz detrás de la confirmación.",
    ["wn_404_release_validation"] = "Interno — La CI comprueba ahora la sintaxis Lua 5.1, el XML, los valores secretos, las pruebas de regresión y el grafo de carga del paquete. El generador detecta referencias ausentes, con mayúsculas incorrectas, cíclicas o externas y un orden de inicio inválido, también de forma fiable en Windows.",
    ["wn_404_secret_reference"] = "Novedad — TomoMod incluye ahora una referencia generada de las API con valores secretos de WoW 12.1.0. Registra casi 4.000 entradas APIDocumentation del cliente, entre ellas 82 métodos de widgets que pueden devolver valores protegidos y 85 funciones que rechazan argumentos secretos.",
    ["wn_404_secret_audit"] = "Cambio — La auditoría combina la referencia del cliente con las pruebas del repositorio, añade informes opcionales de widgets, evidencias, incoherencias y JSON, y utiliza rutas de baseline portátiles. Su conjunto ampliado de 70 pruebas pasa sin nuevos hallazgos de publicación.",
})

TomoMod_RegisterLocale("itIT", {
    ["wn_404_tomohdv_buy_layout"] = "Correzione — TomoHDV V3.2 tiene quantità, totale e stato lontani dal pulsante di acquisto sugli schermi ultrawide e con scale dell'interfaccia ridotte. L'intero flusso di acquisto diretto resta ora entro l'altezza disponibile della scheda oggetto.",
    ["wn_404_tomohdv_buy_final_polish"] = "Modifica — TomoHDV V3.3 sposta i controlli di acquisto diretto in una scheda dedicata, estesa tra le schede dei prezzi e il pulsante di conferma. La quantità non può più salire sulle schede dei prezzi con nessuna scala dell'interfaccia, e la scheda oggetto più alta e leggermente più larga lascia più spazio al totale stimato e alla riga di stato.",
    ["wn_404_nameplates_secret_power"] = "Correzione — Il rilevamento dei ruoli nelle spedizioni con seguaci controlla se UnitPowerMax ha restituito un valore protetto prima di confrontarlo. Se il mana non è leggibile, viene usato senza errori il ruolo assaltatore nei contenuti limitati.",
    ["wn_404_unitclass_safety"] = "Correzione — Forge, Damage Meter, Resource Bars, la schermata AFK, Cooldown Manager e Resource Cast Studio ora filtrano i risultati di UnitClass prima di cercare i colori di classe. Se la classe è protetta, ogni interfaccia usa un valore alternativo sicuro invece di generare un errore.",
    ["wn_404_profile_recovery"] = "Novità — TomoMod conserva le cinque copie di ripristino più recenti. Profili > Reimpostazioni e i comandi /tm backup permettono di crearle, elencarle e ripristinarle; importazioni, layout, preset e reimpostazioni creano automaticamente un punto di ritorno e annullano le modifiche in caso di errore.",
    ["wn_404_import_safety"] = "Modifica — Le importazioni complete, selettive e come profilo nominato sono ora transazionali, limitate e disponibili fuori dal combattimento. Dati troppo grandi o profondi, eseguibili, ciclici, con metatabelle, numeri non finiti, valori non validi o impostazioni non trasferibili vengono rifiutati prima di modificare il database attivo.",
    ["wn_404_layout_share_safety"] = "Correzione — Le stringhe di condivisione del layout e i nomi dei punti di navigazione mantengono maiuscole e minuscole invece di essere alterati dai comandi. L'importazione accetta solo ancoraggi e percorsi dei caratteri dichiarati, valida ogni posizione e conserva la scalatura per risoluzione in una transazione recuperabile.",
    ["wn_404_interface_reliability"] = "Correzione — La chiusura delle opzioni salva in modo affidabile il profilo attivo, le finestre di ricarica e importazione restano in primo piano, il trascinamento delle aure ignora coordinate incomplete e l'analisi Mitica+ usa ora l'accento condiviso di TomoMod.",
    ["wn_404_studio_return"] = "Novità — L'apertura di qualsiasi Studio ora nasconde sempre l'interfaccia di TomoMod. Chiudendo gli Studio Mitica+, Gruppo e Incursione, Risorse e Lancio o Astral Forge la si riapre; Cooldown Studio mantiene invece la propria uscita con ricarica di sicurezza senza riaprire l'interfaccia dietro la conferma.",
    ["wn_404_release_validation"] = "Interno — La CI controlla ora sintassi Lua 5.1, XML, valori segreti, test di regressione e grafo di caricamento del pacchetto. Il generatore rileva riferimenti mancanti, con maiuscole errate, ciclici o esterni e un ordine di inizializzazione non valido, anche in modo affidabile su Windows.",
    ["wn_404_secret_reference"] = "Novità — TomoMod include ora un riferimento generato delle API con valori segreti di WoW 12.1.0. Registra quasi 4.000 voci APIDocumentation del client, tra cui 82 metodi dei widget che possono restituire valori protetti e 85 funzioni che rifiutano argomenti segreti.",
    ["wn_404_secret_audit"] = "Modifica — Il controllo combina il riferimento del client con le prove del repository, aggiunge report facoltativi per widget, prove, incoerenze e JSON e usa percorsi di baseline portabili. La suite ampliata di 70 test viene superata senza nuovi rilievi di pubblicazione.",
})

TomoMod_RegisterLocale("ptBR", {
    ["wn_404_tomohdv_buy_layout"] = "Correção — O TomoHDV V3.2 mantém quantidade, total e estado longe do botão de compra em telas ultrawide e com escalas reduzidas da interface. Todo o fluxo de compra direta agora permanece dentro da altura disponível da ficha do item.",
    ["wn_404_tomohdv_buy_final_polish"] = "Alteração — O TomoHDV V3.3 move os controles de compra direta para um cartão próprio, esticado entre os cartões de preço e o botão de confirmação. A quantidade não pode mais subir sobre os cartões de preço em nenhuma escala da interface, e a ficha do item, mais alta e um pouco mais larga, dá mais espaço ao total estimado e à linha de estado.",
    ["wn_404_nameplates_secret_power"] = "Correção — A detecção de função em masmorras com seguidores verifica se UnitPowerMax retornou um valor protegido antes de compará-lo. Se a mana não puder ser lida, a função volta com segurança para dano em conteúdo restrito.",
    ["wn_404_unitclass_safety"] = "Correção — Forge, Damage Meter, Resource Bars, a tela AFK, Cooldown Manager e Resource Cast Studio agora filtram os resultados de UnitClass antes de consultar as cores de classe. Se a classe estiver protegida, cada interface usa um valor alternativo seguro em vez de causar um erro.",
    ["wn_404_profile_recovery"] = "Novidade — TomoMod mantém os cinco backups de recuperação mais recentes. Perfis > Redefinições e os comandos /tm backup permitem criar, listar e restaurar; importações, layouts, presets e redefinições criam automaticamente um ponto de retorno e desfazem as alterações se ocorrer um erro.",
    ["wn_404_import_safety"] = "Alteração — Importações completas, seletivas e como perfil nomeado agora são transacionais, limitadas e disponíveis apenas fora de combate. Dados grandes ou profundos demais, executáveis, cíclicos, com metatabelas, números não finitos, valores inválidos ou configurações não portáveis são rejeitados antes de alterar o banco ativo.",
    ["wn_404_layout_share_safety"] = "Correção — Códigos de compartilhamento de layout e nomes de pontos de destino mantêm maiúsculas e minúsculas em vez de serem alterados pelo interpretador de comandos. A importação aceita apenas âncoras e caminhos de fonte declarados, valida cada posição e preserva a escala por resolução em uma transação recuperável.",
    ["wn_404_interface_reliability"] = "Correção — Fechar as opções salva o perfil ativo de forma confiável, janelas de recarga e importação ficam acima delas, o arraste de auras ignora coordenadas incompletas e a análise de Mítica+ agora usa a cor de marca compartilhada do TomoMod.",
    ["wn_404_studio_return"] = "Novidade — Abrir qualquer Studio agora sempre oculta a interface do TomoMod. Fechar os Studios de Mítico+, Grupo e Raide, Recursos e Lançamentos ou Astral Forge volta a abri-la; o Studio de Recargas mantém sua saída com recarga de segurança sem abrir a interface atrás da confirmação.",
    ["wn_404_release_validation"] = "Interno — A CI agora verifica sintaxe Lua 5.1, XML, valores secretos, testes de regressão e o grafo de carregamento do pacote. O gerador detecta referências ausentes, com maiúsculas incorretas, cíclicas ou externas e ordem de inicialização inválida, também de forma confiável no Windows.",
    ["wn_404_secret_reference"] = "Novidade — O TomoMod agora inclui uma referência gerada das APIs com valores secretos do WoW 12.1.0. Ela registra quase 4.000 entradas APIDocumentation do cliente, incluindo 82 métodos de widgets que podem retornar valores protegidos e 85 funções que rejeitam argumentos secretos.",
    ["wn_404_secret_audit"] = "Alteração — A auditoria combina a referência do cliente com evidências do repositório, adiciona relatórios opcionais de widgets, evidências, inconsistências e JSON e usa caminhos de baseline portáveis. A suíte ampliada de 70 testes passa sem novos achados de lançamento.",
})
